# Introduction

In [8]:
# Imports
import numpy as np

## Lab 1

In [9]:
M = np.array(([1,0], [0,1])) ## Numpy Matrix
print(M)

[[1 0]
 [0 1]]


In [10]:
## adding Matrix
print(M + M)

[[2 0]
 [0 2]]


In [11]:
## Special Matrix (not matrix)
N = np.array(([0, 1], [1, 0]))

In [12]:
print(N * N) ## Get Not Matrix back


[[0 1]
 [1 0]]


In [13]:
## numpy overloads '@' operator,

print(N @ N) ## Gives back identiy matrix

[[1 0]
 [0 1]]


## Column Vectors

In [14]:
x = np.array([[0.75], [0.25]])
print(x.sum())

1.0


## Problem 1: Generating Random Boolean Functions
### Defining four constant and balanced functions

In [ ]:
# Const func
def f1(a, b, c, d):
    "Always returns 0"
    return 0

# balanced function
def f2(a, b, c, d):
    "Identity function"
    return a

# balanced function
def f3(a, b, c, d):
    "Not function"
    return a ^ b ^  c ^ d

# const function
def f4(a, b, c, d):
    "const function"
    return 1

## Problem 2: Classical Testing for Function Type

## Problem 3: Quantum Oracles

## Problem 4: Deutsch's Algorithm with Qiskit

## Problem 5: Scaling to the Deutsch–Jozsa Algorithm